# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'ordering': ('order_index', '-create_time'), 'verbose_name': '短信验证码', 'verbose_name_plural': '短信验证码'},
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='add_time',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifycode',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verifycode',
            name='order_index',
            field=models.IntegerField(default=1000),
        ),
    ]
