# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_auto_20190206_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order_index', models.IntegerField(default=1000)),
                ('name', models.CharField(default=None, max_length=100, verbose_name='姓名')),
                ('email', models.CharField(default=None, max_length=100, verbose_name='邮箱')),
                ('website', models.CharField(blank=True, default=None, max_length=100, verbose_name='个人主页')),
                ('comment', models.TextField(max_length=1000, verbose_name='留言')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Article', verbose_name='关联文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ('order_index', '-create_time'),
            },
        ),
    ]
