# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190129_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(0, '程序人生'), (1, '前端'), (2, '架构'), (3, '区块链'), (4, '游戏开发'), (5, '移动开发'), (6, '云计算'), (7, '计算机基础')], default=0),
        ),
    ]
