# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_featured_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_desc',
            field=models.CharField(default=None, max_length=250, verbose_name='简介'),
        ),
    ]
