# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_desc',
            field=models.TextField(default=None, max_length=250, verbose_name='简介'),
        ),
    ]
